### ISSUE TITLE
explicit membership status

### ISSUE THREAD

**Issue by patte** [orbiting/republik-admin-frontend#22]
![screenshot from 2018-11-27 15-10-29](https://user-images.githubusercontent.com/3500621/49087199-a5f1da00-f256-11e8-9eab-3ba1c244295d.png)

Right now, the admin frontend shows `ACTIVE` / `INACTIVE` in the membership list. It's not clear to me if that indicates the `active` flag or the `renew` flag or a combination of both. I'd wish have a clear title, and both fields exposed in the detail table to the membership.

Additionally: It would be good if the pledges and memberships would be sorted by `createdAt DESC`. Now I come across overviews, where memberships are sorted by `createdAt ASC` and pledges by `createdAt DESC`.

**Comment by pae-blue** [comment]
Fixed in #31
